"""create client and compound and trial tables

Revision ID: 00002
Revises: 00001
Create Date: 2025-12-16 16:54:35.604742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00002'
down_revision: Union[str, Sequence[str], None] = '00001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('compounds',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compounds_id'), 'compounds', ['id'], unique=False)
    op.create_index(op.f('ix_compounds_name'), 'compounds', ['name'], unique=False)
    op.create_index(op.f('ix_compounds_name_slug'), 'compounds', ['name_slug'], unique=True)
    op.create_table('trials',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trials_id'), 'trials', ['id'], unique=False)
    op.create_index(op.f('ix_trials_name'), 'trials', ['name'], unique=False)
    op.create_index(op.f('ix_trials_name_slug'), 'trials', ['name_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trials_name_slug'), table_name='trials')
    op.drop_index(op.f('ix_trials_name'), table_name='trials')
    op.drop_index(op.f('ix_trials_id'), table_name='trials')
    op.drop_table('trials')
    op.drop_index(op.f('ix_compounds_name_slug'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_name'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_id'), table_name='compounds')
    op.drop_table('compounds')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
